/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/**
 * Optimize a single image buffer — used by the Next.js API route handler.
 * Returns the encoded bytes (WebP by default, or the requested format).
 */
export declare function optimizeImage(input: Buffer, quality?: number | undefined | null, width?: number | undefined | null, height?: number | undefined | null, format?: string | undefined | null): Buffer
export declare function optimizeDirectory(pathStr: string): number
